# numpy :-

list and array difference
list - diffe d t store / slow
array - simeler data type / fast

In [4]:
import numpy as np

In [5]:
x=[1,2,3,4,5]
print(x)
print(type(x))


[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
x=np.array([x])
x

array([[1, 2, 3, 4, 5]])

In [7]:
x=np.array(x)

In [8]:
x.ndim

2

In [9]:
# metrix
# 3*2
x=np.array([[1,2],[3,4],[5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
x.shape

(3, 2)

In [13]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x1.shape

(3, 3)

In [19]:
# 2*4 
x2=np.array([[[1,2,3,4],[5,6,7,8],[]]])
# x=np.array([[5,7,3,3],[5,6,9,5]])
x2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [21]:
x.shape

(3, 2)

# random ---> 3 kinds of Distribution
* rand()
* randin()
* randint()

In [22]:
# 0 to 1 
x =np.random.rand(10)
x

array([0.96559693, 0.69924932, 0.27167791, 0.09147785, 0.57823376,
       0.59679606, 0.3432955 , 0.4310186 , 0.18973031, 0.70842955])

In [27]:
# randn # -3 to 3
x=np.random.rand(5,2)
x

array([[0.80130815, 0.89096063],
       [0.95590143, 0.22820085],
       [0.56965545, 0.7695319 ],
       [0.47070183, 0.92392081],
       [0.05541108, 0.62953235]])

In [29]:
# randint()
x=np.random.randint(1,10,100)
x # 10 exclude

array([4, 5, 1, 6, 6, 7, 1, 1, 3, 5, 6, 7, 7, 7, 1, 3, 3, 7, 2, 7, 6, 5,
       1, 4, 5, 2, 9, 7, 5, 5, 9, 3, 4, 2, 4, 2, 3, 1, 8, 6, 6, 9, 9, 9,
       9, 2, 8, 9, 1, 4, 5, 5, 7, 7, 8, 9, 2, 7, 3, 3, 3, 5, 9, 7, 8, 5,
       4, 5, 5, 8, 9, 4, 2, 2, 6, 6, 9, 2, 8, 3, 4, 4, 7, 4, 3, 6, 5, 2,
       1, 7, 4, 3, 1, 6, 8, 8, 3, 2, 8, 4], dtype=int32)

In [31]:
# Arange() function
x=np.arange(1,100)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [32]:
x=np.arange(1,100,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [33]:
x=np.arange(-100,100,5)
x

array([-100,  -95,  -90,  -85,  -80,  -75,  -70,  -65,  -60,  -55,  -50,
        -45,  -40,  -35,  -30,  -25,  -20,  -15,  -10,   -5,    0,    5,
         10,   15,   20,   25,   30,   35,   40,   45,   50,   55,   60,
         65,   70,   75,   80,   85,   90,   95])

In [34]:
#  useless function
# 1. 0 0
# 0 1 0
# 0 0 1

x = np.eye(5,2)
x

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
x = np.eye(5,5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
x=np.zeros([5,2]) # 0
x

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
# ones
x = np.ones([2,3])
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [1]:
import numpy as np

In [2]:
a[a>3]

NameError: name 'a' is not defined

In [3]:
a[a%2==0]

NameError: name 'a' is not defined

In [5]:
a[a%2!=0]

NameError: name 'a' is not defined

In [6]:
x=np.array([[1,2,3,4,14],[3,5,6,17,24]])
x

array([[ 1,  2,  3,  4, 14],
       [ 3,  5,  6, 17, 24]])

In [7]:
z=x.reshape(5,2)
z

array([[ 1,  2],
       [ 3,  4],
       [14,  3],
       [ 5,  6],
       [17, 24]])

In [13]:
a=np.array[[[1,2,3,4,5],[6,7,8,9,0],[55,66,77,88,4]]]
a

TypeError: 'builtin_function_or_method' object is not subscriptable

In [15]:
# linespace -- no qual devided
x=np.linspace(1,10,18)
x

array([ 1.        ,  1.52941176,  2.05882353,  2.58823529,  3.11764706,
        3.64705882,  4.17647059,  4.70588235,  5.23529412,  5.76470588,
        6.29411765,  6.82352941,  7.35294118,  7.88235294,  8.41176471,
        8.94117647,  9.47058824, 10.        ])

In [17]:
x=np.linspace(1,20,20)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [18]:
a=np.array([3,5,8,4,7,9]).reshape(3,2)
b=np.array([4,6,9,2,4,8]).reshape(3,2)

In [19]:
np.concatenate((a,b))

array([[3, 5],
       [8, 4],
       [7, 9],
       [4, 6],
       [9, 2],
       [4, 8]])

In [ ]:
# Arithmetic operations
a =np.array([[3,1],[2,-1]])


In [20]:
a=np.array([[3,1],[2,-1]])
b=np.array([[2,-2],[5,1]])

In [21]:
from numpy.linalg import matrix_power as mpow

In [ ]:
3 1   3  1
2 -1  2  -1





In [22]:
mpow(a,3)

array([[37,  9],
       [18,  1]])

In [23]:
a@a@a

array([[37,  9],
       [18,  1]])